### ISSUE TITLE
Text alignment issue in IE11 for Page heading

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#100]
**Describe the bug**
Products heading isn't aligned to the rest of the text in IE11 when screen resolution is larger than 1024x768

**To Reproduce**
Pre-condition: Using Windows 10, IE11 on screen resolution 1680 x 1050
1) Access the MHRA website
2) Search for a valid phrase 

**Expected behavior**
The heading Products should align to the left hand side

**Screenshots**
<img width="1390" alt="Screenshot 2019-12-10 at 16 23 32" src="https://user-images.githubusercontent.com/6122821/70547880-9398c480-1b69-11ea-9dbc-1da53c3c254b.png">

**Additional context**
Have originally checked with browserstack, but later confirmed it with a real windows machine

This occurs on all pages, including homepage and About page: 
<img width="1184" alt="Screenshot 2019-12-10 at 16 27 44" src="https://user-images.githubusercontent.com/6122821/70548231-191c7480-1b6a-11ea-85da-0affcd66a7be.png">

**Comment by craiga** [comment]
No longer an issue 🎉
