### ISSUE TITLE
Bullet points don't appear on About Us Page

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#101]
**Describe the bug**
The bullet points don't display on Chrome on the about us page 

**To Reproduce**
When using Chrome and going to the about page, the bullet points don't appear for the EMA links. They are present in the markdown page (Lines 50 + 51)  

**Expected behavior**
The bullet points should appear on Chrome otherwise the text looks misaligned. 

**Screenshots**
<img width="1072" alt="Screenshot 2019-12-10 at 16 49 24" src="https://user-images.githubusercontent.com/6122821/70550017-0bb4b980-1b6d-11ea-8dd2-59a8cfa54bc1.png">

**Comment by m-doughty** [comment]
@DimplePatel This is intentional as per the Zeplin design.
https://app.zeplin.io/project/5dd51ae21205c944f8c1d35b/screen/5dea7c677a62584b2d341204

**Comment by DimplePatel** [comment]
@m-doughty can the bullet point be removed then so the list aligns to the left?
