### ISSUE TITLE
Accessibility - there's no message to say the active substance filter found no results

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#104]
**Describe the bug**
When you select a letter or number filter for the list of active substances which brings up 0 results, there is no message telling the user this. This is an issue for accessibility (see https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-identified.html)  and also may result in users thinking the list may not have loaded.

**To Reproduce**
1) Go to https://mhraproductsdev.z33.web.core.windows.net/
2) Scroll down and select the filter '6' under List of active substances
3) The page reloads but nothing visually has changed inside the page

**Expected behavior**
The user is ideally informed there are no active substances to display

**Screenshots**
<img width="1427" alt="Screenshot 2019-12-10 at 17 10 35" src="https://user-images.githubusercontent.com/6122821/70551733-01e08580-1b70-11ea-89c5-acb853b6019a.png">

**Comment by roughprada** [comment]
Can we group numbers into 0-9?

**Comment by DimplePatel** [comment]
This is the way the current website works, i wasn't sure if the decision to separate the numbers out was on purpose?

**Comment by DimplePatel** [comment]
If there's no strong reason to separate 0-9 in the filter, it seems like a nice solution to me because all the letters have results, the numbers are the problem

**Comment by roughprada** [comment]
@m-doughty is this an option?

**Comment by StuartHarris** [comment]
@roughprada it's complicated and would require us calling the server 10 times and concatenating the results. Not ideal. Would be easier to leave it how it is.

**Comment by StuartHarris** [comment]
@roughprada - in skateboard we will have an API and it will be a *lot* easier.
