### ISSUE TITLE
Small text inconsistencies in About page

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#105]
**Describe the bug**
https://mhraproductsdev.z33.web.core.windows.net/about/

1) A PIL will be based on an SPC.  
This should probably say 'a SPC' because SPC starts with a consonant.
2)  product’s lifecycle,so 
There's a missing space after the comma

**Screenshots**
<img width="1106" alt="Screenshot 2019-12-10 at 17 25 40" src="https://user-images.githubusercontent.com/6122821/70552925-1b82cc80-1b72-11ea-8966-68e59285511c.png">

**Comment by StuartHarris** [comment]
Thanks Dimple! I think "an" is correct before "SPC" because it's an acronym which is effectively spelt `ess-pee-see`. But the other needs fixing. Feel free to raise a PR :-) or we can do it.

**Comment by DimplePatel** [comment]
Have retested this on master and its now fixed
