### ISSUE TITLE
New Disclaimer copy

### ISSUE THREAD

**Issue by KyleCMHRA** [MHRA/products#108]
Please read and confirm the below information, which refers to accessing SPC or PIL documents

I understand that this information is a copy of the Summary of Product Characteristics and patient information leaflet for a medicine, which outline the conditions under which the medicine should be used and information on its known safety.

I understand that this information may be updated several times within its shelf life, and that there could be differences between the version of the information shown here and other information in the public domain.

I understand that the MHRA is unable to offer medical advice and that if a patient has any questions about a medicine they are taking they should contact their doctor or pharmacist. Patients should not stop taking any prescribed medicines without first speaking to a healthcare professional. Suspected adverse reactions to a medicine can be reported to us on a[ Yellow Card](http://yellowcard.mhra.gov.uk/)

I understand that the MHRA has used its best endeavours in publishing this information, but accept that the information may not be the most up to date version for this product.

[ Tick Box ] I have read and understand the disclaimer [

**Comment by DimplePatel** [comment]
Hi @KyleCMHRA  can i just check that this is the final copy you want in? 
The differences I can between this and the copy currently in is that the first paragraph is missing and Yellow card isn't a hyperlink:
<img width="908" alt="Screenshot 2019-12-11 at 13 22 19" src="https://user-images.githubusercontent.com/6122821/70624938-483def00-1c19-11ea-8526-cf6796dc5d9a.png">

**Comment by KyleCMHRA** [comment]
Yeah it needs the link to Yellow Card, and it also needs the first bit of wording. Otherwise correct, it's the same. Thanks.

**Comment by DimplePatel** [comment]
updated now
