### ISSUE TITLE
Sometimes file names are too long and have multiple brand names

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#127]
**Describe the bug**
When filtering active substances, sometimes the file names are really long and include multiple brand names 

**To Reproduce**
1) go to https://mhraproductsdev.z33.web.core.windows.net/?substance=CAFFEINE and scroll
2) notice long file names such as "COLD & FLU RELIEF CAPSULES,SPAR COLD RELIEF CAPSULES,TODAYS SELECT COLD RELIEF CAPSULES,TESCO HEALTH COLD & FLU RELIEF CAPSULES,SAINSBURYS HEALTHCARE SINUS DUAL RELIEF CAPSULES,BOOTS BLOCKED NOSE & HEADACHE RELIEF CAPSULES,SUPERDRUG PARACETAMOL COLD RELIEF WITH DECONGESTANT,BOOTS COLD & FLU RELIEF CAPSULES,HEALTH ESSENTIALS COLD RELIEF CAPSULES,NON-DROWSY DECONGESTANT WITH PARACETAMOL,WILKO NON-DROWSY DECONGESTANT WITH PARACETAMOL,THE LOCAL INDEPENDENT TRADING COMPANY LTD COLD RELIEF CAPSULES,ESSENTIAL WAITROSE COLD & FLU RELIEF CAPSULES,COLD RELIEF CAPSULES (12 files)"

**Expected behavior**
File names should be shorter and with 1 brand name so users know what they are searching for

**Reproducability**
This doesn't seem to be a common issue whilst testing different active substances

**Screenshots**
<img width="1435" alt="Screenshot 2019-12-11 at 15 57 31" src="https://user-images.githubusercontent.com/6122821/70637351-fc964000-1c2e-11ea-9b11-25e37209adde.png">

Another good example is https://mhraproductsdev.z33.web.core.windows.net/?substance=CAPSICUM%20TINCTURE

**Comment by m-doughty** [comment]
> File names should be shorter and with 1 brand name so users know what they are searching for
This is a problem with the input data. I'm not sure what the best solution to this is, we could cut them off at say 80 characters and add ellipsis client side? Thoughts @MHRA/products-dev?

**Comment by DimplePatel** [comment]
I think real issue is that file names aren't correct - it seems that each phrase/brand is separated by a comma however the file names in the application were bundling them together

**Comment by m-doughty** [comment]
> I think real issue is that file names aren't correct - it seems that each phrase/brand is separated by a comma however the file names in the application were bundling them together
> 
> So for instance, it should just probably show 'Extra power pain reliever caplets' and nothing else

How would we know which part of the file name is correct?

**Comment by DimplePatel** [comment]
Good point. 
In this example, https://mhraproductsdev.z33.web.core.windows.net/?&product=true&page=1&search=ENERGYSTORE%20EXTRA%20TABLETS%2CWILKO%20ENERGY%20EXTRA%20TABLETS%2CSUPERDRUG%20PICK%20UP%2CSAINSBURYS%20ENERGY%20EXTRA%20TABLETS%2CTESCO%20HEALTH%20ENERGY%20TABLETS 
The brand name is also present in the PDF name . The PL numbers for the products are all the same

**Comment by m-doughty** [comment]
> Good point.
> In this example, https://mhraproductsdev.z33.web.core.windows.net/?&product=true&page=1&search=ENERGYSTORE%20EXTRA%20TABLETS%2CWILKO%20ENERGY%20EXTRA%20TABLETS%2CSUPERDRUG%20PICK%20UP%2CSAINSBURYS%20ENERGY%20EXTRA%20TABLETS%2CTESCO%20HEALTH%20ENERGY%20TABLETS
> The brand name is also present in the PDF name . The PL numbers for the products are all the same

This is presumably because it's a generic product sold by multiple vendors. I don't think there's a simple way to fix this issue because these brand names are just parts of a long string, and cutting some of them out would make search less effective.
