### ISSUE TITLE
Not applicable is listed as an active substance

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#136]
**Describe the bug**
Not applicable is listed as an active substance

**To Reproduce**
https://mhraproductsdev.z33.web.core.windows.net/?substance=NOT%20APPLICABLE
1) Go to MHRA website
2) Filter for 'n' under active substances
3) Click on Not applicable
4) Note 3 other active substances are listed here: 0.1% W/W POLYSORBATE 80 IN WATER FOR INJECTION (2 files)
METHADOSE DILUENT,METHADONE DILUENT (1 files)
STERILE DILUENT FOR HUMATROPE SOLVENT FOR SOLUTION FOR INJECTION (1 files)

**Expected behavior**
The 3 active substances listed on the 2nd level should be either on the first level under the correct letter/number, or under the 2nd level of the correct substance. 

**Screenshots**
![Screenshot 2019-12-11 at 20 25 38](https://user-images.githubusercontent.com/6122821/70657786-6c6af180-1c54-11ea-9fc7-db607ea68654.png)

**Additional context**

**Comment by StuartHarris** [comment]
Before we fix this we should check with the business that this is not actually the desired/correct behaviour.
