### ISSUE TITLE
There are missing active substances on the new site vs old one

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#137]
**Describe the bug**
I did a comparison between the old site and new, counting the numbers of active substances listed on the first level. There are missing active substances on new site. 

**To Reproduce**

Examples of substances listed on old site but not on the new are:
- IBANDRONATE SODIUM 
- THIOPENTAL SODIUM AND SODIUM CARBONATE
- TETRAETHYLTHIURAM DISULPHIDE 

For the first example , two PDFs are present on the old website: http://www.mhra.gov.uk/spc-pil/index.htm?prodName=IBANDRONIC%20ACID%206%20MG%20CONCENTRATE%20FOR%20SOLUTION%20FOR%20INFUSION&subsName=IBANDRONATE%20SODIUM&pageID=SecondLevel 

For second example, PDFS are also present on the old website http://www.mhra.gov.uk/spc-pil/index.htm?prodName=THIOPENTAL%201%20G%20POWDER%20FOR%20SOLUTION%20FOR%20INJECTION&subsName=THIOPENTAL%20SODIUM%20AND%20SODIUM%20CARBONATE&pageID=SecondLevel

**Comment by m-doughty** [comment]
@DimplePatel Can you please reload the website and confirm these all show? This was due to the indexing not having finished when this issue was submitted.

**Comment by DimplePatel** [comment]
me and stu have found an issue here @m-doughty  i'm just going to update the ticket

**Comment by m-doughty** [comment]
Spoke to @StuartHarris and we don't believe this is because we're de-duping. We need access to the Oracle database to confirm our thoughts.

**Comment by DimplePatel** [comment]
Extra info - There are only 3 letters with missing active substances: T, I and P. 
Whilst T and I are only missing 2 each, P is missing 47
