### ISSUE TITLE
Learning modules - SSRI - missing footnotes

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#141]
**Describe the bug**
Missing footnotes on 2 pages for SSRI

**To Reproduce**
https://mhracpddev.z33.web.core.windows.net/ssri/CON146583_3
There are footnotes referenced in the table but none are present at the bottom of the page

https://mhracpddev.z33.web.core.windows.net/ssri/CON146583_21
Only 1 footnote is present at the bottom of this page but more are referenced in the table

**Expected behavior**
Footnotes should be present at the bottom of the page for all references in both tables .

**Screenshots**
<img width="1440" alt="Screenshot 2019-12-12 at 11 52 39" src="https://user-images.githubusercontent.com/6122821/70709923-f313e300-1cd5-11ea-8128-0a6b9dd7bf2d.png">

**Additional context**

**Comment by craiga** [comment]
This should be addressed by https://github.com/MHRA/products/pull/125.

**Comment by DimplePatel** [comment]
fixed now
