### ISSUE TITLE
[disclaimer] Missing copy

### ISSUE THREAD

**Issue by roughprada** [MHRA/products#146]
**Describe the bug**
We are missing the product information on the disclaimer screen

**To Reproduce**
Steps to reproduce the behaviour:

1. Make a search (any search is valid)

**Expected behaviour**
The disclaimer screen contains both product information and disclaimer as per design.
Zeplin: https://zpl.io/aNnQZ7N

**Screenshots**
![Screenshot 2019-12-12 at 13 29 18](https://user-images.githubusercontent.com/5957010/70717144-acc68000-1ce5-11ea-9790-a1623bfde4de.png)

**Additional context**

**Comment by DimplePatel** [comment]
https://github.com/MHRA/products/pull/166/

**Comment by DimplePatel** [comment]
this has been fixed now
