### ISSUE TITLE
[Search results] Missing copy

### ISSUE THREAD

**Issue by roughprada** [MHRA/products#148]
**Describe the bug**
We are missing the product information on the search results screens

**To Reproduce**

1. Make a search (any search is valid)

**Expected behavior**
Zeplin: https://zpl.io/blAkq9e

**Screenshots**
![Screenshot 2019-12-12 at 13 48 26](https://user-images.githubusercontent.com/5957010/70717372-1cd50600-1ce6-11ea-9100-e0113373f99e.png)

**Additional context**
N/A

**Comment by DimplePatel** [comment]
https://github.com/MHRA/products/pull/166/

**Comment by DimplePatel** [comment]
this has been fixed now
