### ISSUE TITLE
Disclaimer is displayed even when there are no search results

### ISSUE THREAD

**Issue by nizzah** [MHRA/products#149]
**Describe the bug**

**To Reproduce**

1. Search for 'aabbccdd' or any other term that shows no results.
2. Displays message saying no search results and also the disclaimer statement with checkbox to accept the disclaimer.

**Expected behavior**
Should not show the disclaimer box because there is the information that the disclaimer is referring does not exist.

**Screenshots**

![image](https://user-images.githubusercontent.com/13586858/70717273-eac3a400-1ce5-11ea-967d-98515f3e955e.png)

![image](https://user-images.githubusercontent.com/13586858/70717326-09299f80-1ce6-11ea-87f5-cbc94fb7eee9.png)

**Additional context**

**Comment by DimplePatel** [comment]
tested on master, verified the fix
