### ISSUE TITLE
LEARNING MODULES - Remove survey

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#154]
**Describe the bug**
We need to remove the questionnaire from the Learning Modules as this isn't GDPR complianr. This is section 8.
Module evaluation’ i.e. https://mhracpddev.z33.web.core.windows.net/opioids/CON143740_18/

**To Reproduce**

1. Go to into each learning module
2. Remove section 8 (https://mhracpddev.z33.web.core.windows.net/opioids/CON143740_18) for each learning module

**Expected behavior**
For section 8 to be removed from each learning module

**Comment by DimplePatel** [comment]
PR https://github.com/MHRA/products/pull/157

**Comment by DimplePatel** [comment]
now removed
