### ISSUE TITLE
About This Service - Remove word "Centrally 

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#155]
Raised by Aisling 
**Describe the bug**
About this Service  SPC/PIL Statement
Please remove word ‘centrally’ as it’s sufficient to say that some medicines are licensed by the EMA.

![image](https://user-images.githubusercontent.com/58432596/70721412-67a64c00-1ced-11ea-8246-33da60b137f4.png)

**Comment by DimplePatel** [comment]
will be fixed when this is merged https://github.com/MHRA/products/issues/155

**Comment by DimplePatel** [comment]
fixed
