### ISSUE TITLE
Search - Word Order in Search 

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#156]
Raise by James
**Describe the bug**
Word order doesn’t seem to affect results? So paracetamol headache, you would expect paracetamol products first, but instead headache and indigestion relief returns, which does include paracetamol but in conjuction with other actives. 

Search  paracetamol headache
Would expect paracetamol products first

**Screenshots**
![image](https://user-images.githubusercontent.com/58432596/70722345-054e4b00-1cef-11ea-955e-91a944a6f666.png)

**Additional context**

**Comment by m-doughty** [comment]
Word order not affecting the results is the intended behavior.
