### ISSUE TITLE
No Search Results Page Wording

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#159]
Raised by Aisling
**Describe the bug**
Copy change – please remove ‘central’ from the no search results page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/58432596/70723484-df29aa80-1cf0-11ea-96a1-2ed518fd9c9f.png)

**Comment by DimplePatel** [comment]
will be fixed when this is merged https://github.com/MHRA/products/pull/153

**Comment by DimplePatel** [comment]
fixed
