### ISSUE TITLE
Search Results Page - Remove "central " from wording

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#163]
**Describe the bug**
Copy change – please remove ‘central’ from the search results page wording

**Screenshots**
![image](https://user-images.githubusercontent.com/58432596/70724702-f7022e00-1cf2-11ea-88f0-44dedf2d6f95.png)

**Additional context**

**Comment by DimplePatel** [comment]
going to close as a duplicate of this https://github.com/MHRA/products/issues/159 which has already been fixed
