### ISSUE TITLE
Learning modules - Footnote leads to a 404 error

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#180]
**Describe the bug**
Hyperlink to antimuscarinic doesn't work

**To Reproduce**
1) Go to https://mhracpddev.z33.web.core.windows.net/opioids/CON143740_7 
2) Click on the footnote reference for ^2 under Factors which increase risk
3) The page opened goes to a 404 error 

Same error happens here: https://mhracpddev.z33.web.core.windows.net/ssri/CON146583_2 when clicking ^5

And here: https://mhracpddev.z33.web.core.windows.net/antipsychotics/CON155606_41 when clicking ^1

**Expected behavior**
The footnote needs to be removed if a replacement can't be found

**Screenshots**

**Additional context**

**Comment by DimplePatel** [comment]
@craiga

**Comment by craiga** [comment]
Footnote on CON146583_2 was already fixed.
