### ISSUE TITLE
Learning Modules - Capitalise SSRI

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#181]
**Is your feature request related to a problem? Please describe.**
The title of the SSRI learning module seems to be in lower case. It's mainly referenced throughout the rest of the text as SSRI, not Ssri. It stands for "selective serotonin reuptake inhibitor", therefore it should be capitilised.

**Describe the solution you'd like**
Update the title of the Learning Module from Ssri to SSRI

**Comment by DimplePatel** [comment]
fixed now
