### ISSUE TITLE
Learning Module- Antipsychotics - Links to NOT FOUND page

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#187]
Raise by Steve
**Describe the bug**
Link to "summary of licensed indications of antipsychotics for adults" in Section 1 Introduction direct to NOT FOUND page

**To Reproduce**

1. In the Antipsychotic Module in the Introduction
2. Click on "summary of licensed indications of antipsychotics for adults" Link
3. Presented with NOT FOUND

**Expected behavior**
Should link to the summary of licensed indications of antipsychotics for adults pdf

**Additional context**
I had been able to access and view the document about 5 minutes previous and when tried to return the Intro page using brower back the pdf did not clear.  refreshed the page and returned to the Intro page and subsequently the link failed

**Comment by craiga** [comment]
Looks like routing might be getting in the way here.

I see a 404 when I click the link,  but clicking refresh in the browser brings up the document.
