### ISSUE TITLE
Search tool cli should create query key for front-end

### ISSUE THREAD

**Issue by StuartHarris** [MHRA/products#206]
**Is your feature request related to a problem? Please describe.**
Terraform does not have an output attribute for the query key used in Azure Search

**Describe the solution you'd like**
We have a search cli tool that currently can create indexes etc. We should enhance that to also create a query key, or retrieve the default (unnamed) one, so that we can configure the UI to use this query key.

**Describe alternatives you've considered**
Using the Portal is not an option as we will not have access to the production Azure account

**Comment by StuartHarris** [comment]
This is the relevant REST API https://docs.microsoft.com/en-gb/rest/api/searchmanagement/querykeys/create

**Comment by m-doughty** [comment]
> This is the relevant REST API https://docs.microsoft.com/en-gb/rest/api/searchmanagement/querykeys/create

Looking at this (and list keys endpoint), it requires OAuth login token, so we would need access to production to use it. However, keys are per resource group so assuming we create all indexes in the same resource group, we wont need to generate a new key to create a new index.
