### ISSUE TITLE
decrease in traffic by 75% 

### ISSUE THREAD

**Issue by sandracoen1405** [MHRA/products#247]
in the last 2 weeks, between the 19/12/19 and the 01/01/20 there has been 4,102 users on the new site.

the 2 weeks before that, between the 05/12/19 and the 18/12/19, there had been 16,200 users on the site

Potential reasons:
- the website does not appear on Google search: it takes to the gov.co.uk website where is the user needs to click on the right link to go to the new site

-redirect does not work when googling "MHRA ibuprofene", we go to a page on the old site, without redirect and with a error message: http://www.mhra.gov.uk/spc-pil/?subsName=IBUPROFEN%20LYSINE&pageID=SecondLevel

- redirect of the old website goes to gov and not to the new website: 
http://www.mhra.gov.uk/spc-pil/
goes to 
https://www.gov.uk/guidance/find-product-information-about-medicines

instead of going directly to 
https://products.mhra.gov.uk/

**Comment by sandracoen1405** [comment]
to solve point:
-redirect does not work when googling "MHRA ibuprofene", we go to a page on the old site, without redirect and with a error message: http://www.mhra.gov.uk/spc-pil/?subsName=IBUPROFEN%20LYSINE&pageID=SecondLevel


Craig provided a list of pages from the old website  (see attachment) to Kyle, so that Kyle could redirect them to the gov.co.uk page.


the other points will need to be discussed next week:

the website does not appear on Google search: it takes to the gov.co.uk website where is the user needs to click on the right link to go to the new site


redirect of the old website goes to gov and not to the new website:
http://www.mhra.gov.uk/spc-pil/
goes to
https://www.gov.uk/guidance/find-product-information-about-medicines
instead of going directly to
https://products.mhra.gov.uk/
[Old URLs for redirect.txt](https://github.com/MHRA/products/files/4019507/Old.URLs.for.redirect.txt)
[Old URLs for redirect.txt](https://github.com/MHRA/products/files/4019509/Old.URLs.for.redirect.txt)

**Comment by craiga** [comment]
Links can be found by searching for "[pil site:mhra.gov.uk](https://www.google.com/search?q=pil+site%3Amhra.gov.uk)", "[spc site:mhra.gov.uk](https://www.google.com/search?q=spc+site%3Amhra.gov.uk)", and "[par site:mhra.gov.uk](https://www.google.com/search?q=par+site%3Amhra.gov.uk)".
