### ISSUE TITLE
SEO: structured metadata to site

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#371]
### User want
I want to be able to easily find a drug via a search engine (Google, Bing, etc.). This may be supported by marking up drugs in our HTML.

**Customer acceptance criteria** 

**Technical acceptance criteria**
Microdata should be included as JSON-LD.

Substances are marked up as a Substance  (http://schema.org/Substance)

Drug search results are marked up as drugs (http://schema.org/Drug).

Lists of these things are marked up as lists (https://schema.org/ItemList).

**Data acceptance criteria**

**Testing acceptance criteria** 
Structured data can be viewed using Google's Structured Data Testing Tool https://search.google.com/structured-data/testing-tool/u/0/

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [x] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
# Testing Instructions

_Prerequisites: Chrome with its development tools turned on. You should be able to run the same test in any modern browser with its developer tools._

For each page metadata should be present on, right click anywhere in the browser and click "Inspect". This will bring up Chrome's DevTools, showing the HTML of the web page.

![Screenshot 2020-03-06 at 17 26 03](https://user-images.githubusercontent.com/76330/76107115-0500db80-5fd0-11ea-92fc-074faff40e4a.png)

In this window, right-click on the `html` element at the very top of the document, select "Copy", and then "Copy outerHTML". This will copy the HTML of the entire web site into the clipboard.

![Screenshot 2020-03-06 at 17 28 04](https://user-images.githubusercontent.com/76330/76107087-f9151980-5fcf-11ea-8a39-7ab5ad332932.png)

Next, go to https://search.google.com/structured-data/testing-tool/u/0/. This is a tool which will show you how Google will interpret the structured data encoded in a page. Click on "Code Snippet", paste in the HTML you copied into your clipboard in the previous step, then click "Run Test". This will then show you how Google would parse the structured data embedded in that HTML.

![Screenshot 2020-03-06 at 17 31 34](https://user-images.githubusercontent.com/76330/76107356-65901880-5fd0-11ea-9e93-ada13ebb506a.png)

Finally, check that the data shown is what you expect!
