### ISSUE TITLE
SEO: Improve URLs on site

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#372]
### User want
I want to easily understand what a page is based on its URL. This should help with SEO.

**Customer acceptance criteria** 
Customers can bookmark pages like `/substance?query=ibuprofen` and then access the same information when navigating to these directly as when navigating them within site links.

Browser back button works when navigating back from `/substance` etc.

**Technical acceptance criteria**
Substance pages should be at `/substance?query=/MY%20COOL%20SUBSTANCE`.

Drug index pages should be at
`/substance-index?query=A` for example

Product pages should at `/product?query=MY%20COOL%20PRODUCT`, `/product?query=MY%20COOL%20PRODUCT&page=2`, etc..

Search pages should at `/search?query=MY%20COOL%20PRODUCT`, `/search?query=MY%20COOL%20PRODUCT&page=2`, etc..

Old URLs should be redirected to these URLs.

The number of results that are displayed after clicking on a drug should match the number displayed next to the result when clicking through the -> -> (X files)

This acceptance criteria has changed from the original since dynamic routing for a static site is not possible - e.g. "/product/<product-name>" or "/search/<search-term>". The dynamic part can only be fetched from the query string.

If the site moves to SSR then the urls can be further improved.

**Data acceptance criteria**
@Sandra Coen please tell Sandra the minute the changes are live so she can make the tracking changes
Ask Sandra to QA URL before it goes live

**Testing acceptance criteria** 
- Can click on an index letter and see substances that start with that letter, with a displayed URL of e.g. "/substance-index?query=I"Can click on a substance and see a list of drugs, with a displayed URL of e.g. "/substance?query=IBUPROFEN"
- Can click on a drug and get taken to the products page, with a displayed URL of e.g. "/product?query=IBUPROFENGEL" and see a disclaimer.
- Once the disclaimer is accepted, can see a list of products. 
- Can apply doc type filters and navigate between pages (if there are enough results)
- Can enter a search term on any page, click search and get taken to the search results page, with a URL of e.g. "/search?query=IBUPROFEN&page=1" and see a disclaimer
- Once the disclaimer is accepted, can see search results and can apply doc 
type filters and navigate between pages (if there are enough results)
- Can refresh any page and the page should reload identically
- Can enter an "old" type url - e.g. "https://mhraproductsstaging.z33.web.core.windows.net/?search=ibuprofen&page=1" and get redirected to the new equivalent "https://mhraproductsstaging.z33.web.core.windows.net/search/?query=ibuprofen&page=1".

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Issues found in testing:

* Going to URLs as they're used in the site directly (for example, `http://localhost:3000/product/?product=IBUPROFEN%20200MG%20TABLETS`) results in a 404.
  * If you remove the slash at the end of the path (so `http://localhost:3000/product?product=IBUPROFEN%20200MG%20TABLETS `) the URL works, but the URL is changed in the browser to re-introduce the slash.
* Redirects from old URLs (`http://localhost:3000/?substance=Z&index=true`) redirect to the URL with a slash (`http://localhost:3000/product-index/?index=Z`), resulting in a 404.
* URLs in sitemap.xml are missing a slash between the hostname and the path. For example, `https://products.mhra.gov.uksubstance?substance=IBUPROFEN` is in the sitemap.
* There's also a handful of meaningless URLs in sitemap.xml:
  * `https://products.mhra.gov.uk/product`
  * `https://products.mhra.gov.uk/search`
  * `https://products.mhra.gov.uk/substance`
  * `https://products.mhra.gov.uk/substance-index`

**Comment by craiga** [comment]
Issues found re-testing:

* Request for `/?substance=K&index=true` redirects to `/product-index/?index=K` (404) instead of `/substance-index/?query=K`.
* Request for `/?substance=CAFFEINE&index=` redirects to `/substance/?substance=CAFFEINE` (empty page) instead of `/substance/?query=CAFFEINE` (`substance` instead of `query` in query string).
* Request for `/?product=true&page=1&search=TOPTABS` redirects to `/search/?q=TOPTABS&page=1&doc=&disclaimer=` (empty page) instead of `/product/?query=TOPTABS`.
* Request for `/?search=cool%20medicines&page=1&doc=` redirects to `/search/?q=cool%20medicines&page=1&doc=&disclaimer=` (empty page) instead of `/search/?query=cool%20medicines&page=1` (`q` instead of `query` in query string).
* Meaningless URLs still in sitemap.xml (low priority?):
  * `https://products.mhra.gov.uk/product`
  * `https://products.mhra.gov.uk/search`
  * `https://products.mhra.gov.uk/substance`
  * `https://products.mhra.gov.uk/substance-index`

**Comment by craiga** [comment]
Looks good! ✅ 💯

**Comment by sandracoen1405** [comment]
ok for data QA.
