### ISSUE TITLE
AUTO BATCH PROCESS - API for Sentinel 

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#382]
### User want
As a user I should be able to see the most up to date documents. 

**Customer acceptance criteria** 
Sentinel should be able to upload and delete documents with metadata, and get the status of uploads and deletions

**Technical acceptance criteria**

- API should provide endpoint to post XML or JSON to create an upload request
- API should provide endpoint to post XML or JSON to create a delete request

Probable blockers:

- We need access to the ExpressRoute so Sentinel can communicate with us

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
L

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
QA'd. I've added integration tests in #468
