### ISSUE TITLE
DATA - Get Google to ingest MHRA Product sitemap

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#392]
### User want
As a user I would want to type keyword such as "ibuprofene MHRA" and land directly on the product page on the MHRA product site

**Customer acceptance criteria** 
The business needs to agree that google search will redirect to the MHRA Product website instead of the gov page

**Technical acceptance criteria**

**Data acceptance criteria**
See the increase of google as a source/medium to a ratio similar to the previous website 

See the increase of google as a source/medium to a ratio similar to the previous website 

**Testing acceptance criteria** 
That typing keyword such as "mhra ibuprofene" would take us to the MHRA Product Site

**Size**
XS

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [x] Quality Assurance 
- [x] Release and Validate

**Comment by KaylieGreen1607** [comment]
@sandracoen1405 Can you investigate the potential impact of this feature, by leveraging the existing data. Will help with prioiritisation.
