### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Document Manager sends a create upload message to Service Bus

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#393]
### User want 
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
The DM publishes a "create upload" message to Service Bus with all of the necessary data in.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
LGTM! I can see a create message coming through to the service bus (the blue line).

![Screenshot 2020-03-06 at 13 32 01](https://user-images.githubusercontent.com/76330/76088442-facee500-5faf-11ea-83b0-d1f40c93c585.png)
