### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Service bus

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#394]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
- Terraform config for a service bus (and any other related and necessary infrastructure) that works when run - i.e. creates a service bus resource. 
- Terraform config for [Azure Redis Cache](https://azure.microsoft.com/en-gb/services/cache/)

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
QA'd this and the terraform still runs fine. No need for documentation update.
