### ISSUE TITLE
AUTO BATCH PROCESS - Indexing Strategy

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#396]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
An understanding and plan of how the search index will be kept up to date with changes. If both new files and deleted files get automatically updated in the index successfully as part of those tickets then this is probably not needed. Or the indexer may be set to run once a week in order to synchronize what's actually in the container in case they get out of sync.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
![Successful runs](https://user-images.githubusercontent.com/7150842/77919272-dc999380-7294-11ea-8899-eb923f030c50.png)

Looks like proof that this is working as we expect.
