### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Create service picks up message from subscription

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#421]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
When a "create file" message is published to service bus, the message makes it to a topic and subscription that the Create Service is watching so that it picks up the message.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by m-doughty** [comment]
@rjkerrison will fix the error logs when the queue is empty. Other than this issue, everything seems fine so I'm happy to mark this as QA passes.
