### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Delete service informs State Manager of completion / error

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#422]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Delete service calls sTATE mANAGER with the status of the delete.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by majikandy** [comment]
QA
Status comes back on the job as `Accepted` 
When service worker picks it up it shows the error on standard out

But... the job status remains as `Accepted`

```
{
   "id": "d69aba65-00cf-454f-9665-ff63f0cefab2",
   "status": "Accepted"
}
```

**Comment by majikandy** [comment]
QA'd the whole of delete again.

Can confirm it now works as expected 👍 

```
{
    "id": "3c1cb9a5-370d-4c72-99e8-39c44db944ae",
    "status": {
        "Error": {
           "message": "Cannot find document with content ID CON1579848082866",
           "code": ""
        }
     }
}
```
