### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Document Manager sends a delete file message to Service Bus

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#424]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
The DM publishes a "delete file" message to Service Bus with all of the necessary data in.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Looks good!
