### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Create service uploads file to blob container

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#427]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Create service uploads a file to the blob container. A lot of this code can be pulled from the current import process.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
It looks like the create worker will panic when it can't connect to the SFTP server.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', src/create_manager/sftp_client.rs:10:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After this, the create worker ceases to respond to messages.

To reproduce, fire up the create worker without a running SFTP server.
