### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Create service informs State Manager on completion / error

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#430]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Create service calls the state Manager with the status of the upload - either failed or successful.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Status is updated to "Done" when successful.

When file not found on SFTP server, status is updated to "Couldn't find file" with code "404".

Other errors do not update status. The message is retried over and over again.

**Comment by craiga** [comment]
I think this is by design.

**Comment by craiga** [comment]
Logged #565 about the status of failed jobs not being updated.
