### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Delete service deletes file from blob storage

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#432]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Delete Service deletes the blob from the container. This code is a small tweak on the existing import service, calling "delete_blob" instead of "put_block_blob".

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [x] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Will need to find file in blob storage based on CON number. This may require changing how files are named, or querying based on metadata.

Querying based on metadata may not be possible.

**Comment by StuartHarris** [comment]
One way would be to query the search engine, but it would be an extra round trip :-(

**Comment by majikandy** [comment]
QA

on the dev environment searched for `IDROLAX 2010G` and found

https://mhraproductsdev.z33.web.core.windows.net/product/?query=IDROLAX%2010G

inspected via chrome and found the azure search GET request and response

the response shows the CON number and the storage blob id

```
{
"@odata.context": "https://mhraproductsdev.search.windows.net/indexes('products-index')/$metadata#docs(*)",
"@odata.count": 1,
"value": [
{
"@search.score": 1,
"rev_label": "1",
"metadata_storage_path": "https://mhraproductsdev.blob.core.windows.net/prod-docs/056470172a48965e5a2e70e2259a803b9037608a",
"product_name": "IDROLAX 10G",
"created": "2019-10-04T06:15:00+00:00",
"release_state": "Y",
"keywords": null,
"title": "leaflet MAH BRAND_PLPI 15361-0852.pdf",
"file_name": "CON1570166158450",
"metadata_storage_size": 91268,
"metadata_storage_name": "056470172a48965e5a2e70e2259a803b9037608a",
"doc_type": "Pil",
"suggestions": [],
"substance_name": [
"MACROGOL 4000"
],
"facets": [
"M",
"M, MACROGOL 4000",
"M, MACROGOL 4000, IDROLAX 10G"
],
"is_deleted": null
}
]
}
```

Ran the curl command to delete that item

Refresh of https://mhraproductsdev.z33.web.core.windows.net/product/?query=IDROLAX%2010G shows the item is gone.

using the `metadata_storage_path` id we can see that it is gone from the blob storage too

https://mhraproductsdev.blob.core.windows.net/prod-docs/056470172a48965e5a2e70e2259a803b9037608a

refreshing the azure search url we can see it is also gone from the index
```
{
"@odata.context": "https://mhraproductsdev.search.windows.net/indexes('products-index')/$metadata#docs(*)",
"@odata.count": 0,
"value": []
}
```

Therefore QA successful. 

P.S. this was tested using a local instance of the latest master code as of 9:45am against the dev environment.  This is not QA'd in staging.
