### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Delete service removes deleted file from index

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#433]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Delete service removes the deleted file from the search index, using a HTTP delete request to the Azure API.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by majikandy** [comment]
QA

Tested as part of https://github.com/MHRA/products/issues/432

Success
