### ISSUE TITLE
Necessary Cookies in Cookie Policy

### ISSUE THREAD

**Issue by craiga** [MHRA/products#436]
### User want

As a privacy-minded user, I want to know what necessary cookies the Products and CPD site uses, so that I am fully informed.

### Description

Need to:

* The sentence: You can turn these cookies on or off below, and then save your preferences. This site stores your acceptance of Google Analytics cookies in your browser’s local storage as 'allowStorage'. is added just above the google analytics toggle buttons on https://products.mhra.gov.uk/cookies/

* The sentence: You can turn these cookies on or off below, and then save your preferences. This site stores your acceptance of Google Analytics cookies in your browser’s local storage as 'allowStorage'. is added just above the google analytics toggle buttons on https://cpd.mhra.gov.uk/cookies

**Comment by majikandy** [comment]
merged and works fine on non-prod still

**Comment by craiga** [comment]
![](https://media.giphy.com/media/2m2OtMffBj0qs/giphy.gif)
