### ISSUE TITLE
TECH - fix mobile usability issues flagged by Google

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#443]
Two issues identified.

* Text too small to read
* Clickable elements too close together

![Screen Shot 2020-02-24 at 14 01 11](https://user-images.githubusercontent.com/6436551/75158523-334c0480-570e-11ea-8f89-e66ea9a19a57.png)
![Screen Shot 2020-02-24 at 14 01 01](https://user-images.githubusercontent.com/6436551/75158525-33e49b00-570e-11ea-8c94-09f5c6e63c8c.png)
![Screen Shot 2020-02-24 at 14 00 50](https://user-images.githubusercontent.com/6436551/75158527-3515c800-570e-11ea-9d7c-7bac28c28def.png)

**Comment by gilbertsak** [comment]
Had a look at all pages that had footnotes updated below, spacing is now adequate and links work / scroll down to listed description item :

/antipsychotics/CON155606_12
/antipsychotics/CON155606_31 
/benzodiazepines/CON234573_10
/benzodiazepines/CON234573_13
/benzodiazepines/CON234573_2 
/benzodiazepines/CON234573_6 
/opioids/CON143740_17 
/ssri/CON146583_21 
/ssri/CON146583_3

**Comment by TimboTambo** [comment]
Release activities:
- Deploy these changes to the learning site using automated release flow
