### ISSUE TITLE
TECH - add loading message to results pages

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#480]
### User want
As a user
I want to know when results are still loading in
So that I don't think there are no results and navigate away

**Customer acceptance criteria** 
When the results page (for search or products) is still loading, we should show a message saying "Loading results for <product name>...", which is then replaced with "Showing 30 results for <product name>" once results are loaded (or "No results for <product name>" if there are no results...

**Technical acceptance criteria**

**Data acceptance criteria**
N/A

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [] Quality Assurance 
- [] Release and Validate

**Comment by craiga** [comment]
LGTM! This could be extended to the substance and product list pages, but this is an improvement.
