### ISSUE TITLE
AUTO BATCH - Support XML Requests

### ISSUE THREAD

**Issue by m-doughty** [MHRA/products#486]
Accenture require an XML interface to the `doc-index-updater` API, as the Sentinel system is unable to serialize or deserialize JSON.

**Acceptance Criteria**

- The API should check the `Content-Type` or `Accept` headers. If the header is `application/xml`, then we should deserialize body & serialize response assuming XML rather than JSON;
- This should be implemented so that it's easy to carry forward into future endpoints.

**Stages**

- [x] Backlog
- [x] Discovery
- [x] Dev
- [x] Review
- [ ] QA
- [ ] UAT

**Comment by craiga** [comment]
Given this command:

```
curl -i -X "POST" "http://localhost:8000/documents" \
      -H 'Content-Type: application/xml' \
      -d $'<document>
  <id>id123</id>
  <name>name</name>
  <type>PIL</type>
  <author>author</author>
  <product></product>
  <keywords></keywords>
  <pl_number>pl_number</pl_number>
  <file_source>Sentinel</file_source>
  <file_path>files/MY-TEST-PIL.pdf</file_path>
</document>'
```

…the response is a 415 Unsupported Media Type:

```
HTTP/1.1 415 Unsupported Media Type
content-type: text/plain; charset=utf-8
content-length: 43
date: Mon, 16 Mar 2020 17:13:17 GMT

The request's content-type is not supported
```

I would expect a response indicating that the content type (XML) is supported, and maybe that the XML itself is badly formatted.

**Comment by m-doughty** [comment]
> Given this command:
> 
> ```
> curl -i -X "POST" "http://localhost:8000/documents" \
>       -H 'Content-Type: application/xml' \
>       -d $'<document>
>   <id>id123</id>
>   <name>name</name>
>   <type>PIL</type>
>   <author>author</author>
>   <product></product>
>   <keywords></keywords>
>   <pl_number>pl_number</pl_number>
>   <file_source>Sentinel</file_source>
>   <file_path>files/MY-TEST-PIL.pdf</file_path>
> </document>'
> ```
> 
> …the response is a 415 Unsupported Media Type:
> 
> ```
> HTTP/1.1 415 Unsupported Media Type
> content-type: text/plain; charset=utf-8
> content-length: 43
> date: Mon, 16 Mar 2020 17:13:17 GMT
> 
> The request's content-type is not supported
> ```
> 
> I would expect a response indicating that the content type (XML) is supported, and maybe that the XML itself is badly formatted.

I believe the issue here is that you haven't sent the `accept` header, and the endpoint expects both.

**Comment by craiga** [comment]
Issues discovered while testing this ticket:

* Requires both an `Accept` and a `Content-Type` header.
  * `Content-Type` is supposed to specify the encoding of the **request**.
  * `Accept` is supposed to specify the encoding of the **response**.

  It's fair enough that Stellent should send both of these headers, but the endpoint strictly shouldn't require both.
* If either of these headers are missing, or if the XML request is malformed in any way, a `415 Unsupported Media Type` response is served up with the body `The request's content-type is not supported`. This is incorrect.

Neither of these should hold up the progress of this feature, but they should be logged as bugs. Putting them together is WIP.
