### ISSUE TITLE
Reports from import process

### ISSUE THREAD

**Issue by StuartHarris** [MHRA/products#49]
We should modify the importer so that it reports which documents it has seen before (i.e. duplicates) and for which documents it has no metadata. This will allow us to more easily compare source and target in order to ensure that the import is correct.

**Comment by m-doughty** [comment]
Adding to this, would be nice to see how many total documents it has uploaded.

**Comment by m-doughty** [comment]
Further to discussion with @StuartHarris, this should show:

- Number of documents not imported because they're unreleased;
- Number of skipped duplicates with a list;
- Number of skipped documents because they have no metadata.

This ticket also includes scope to avoid uploading duplicates.
