### ISSUE TITLE
Some cookies still present after clear

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#498]
**Describe the bug**
After accepting cookies and then turning them off, some cookies are still present (`_ga` and `_gat`).

**To Reproduce**
1) Accept all cookies. 
2) Go to cookie policy page and disable cookies then save
3) Examine cookies in developer tools
4) Navigate to another page
5) See `_ga` and `_gat` cookies get added back 

**Expected behavior**
They should clear and remain cleared once cookies are set to disabled.

**Screenshots**
N/A

**Additional context**
Not sure if this has ever worked fully as intended.

**Comment by craiga** [comment]
In QA, I found that cookies are being cleared effectively, but when the user clicks "Accept all cookies":
 * cookies aren't being set; and
 * Google Analytics isn't being activated.

In order for both of these to happen.

I think we need to trigger a page reload after allowing cookies for Google Analytics to do its initialisation.

**Comment by m-doughty** [comment]
I'm comfortable saying that this works as intended in Brave, but I can't test in Safari.

**Comment by majikandy** [comment]
I can confirm this works on Dev environment in both `Safari` and `Chrome` on a mac.
<img width="1385" alt="Screenshot 2020-03-24 at 11 31 28" src="https://user-images.githubusercontent.com/444711/77421062-106f4780-6dc3-11ea-99d0-4d450ee5b2c3.png">

moving forward to ready for UAT

**Comment by AndySnowMHRA** [comment]
Hi there still appear to be some analytics in Edge browser (unless I am reading it wrong. working fine in Chrome.
