### ISSUE TITLE
Searching for a term with "%" in throws error

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#511]
**Describe the bug**
Searching for a term with "%" in throws error and causes next.js to crash.

**To Reproduce**
1) Search for `bacteriostatic solvent (0.3%w/v metacresol in wfi)` 
2) Observe error page

**Expected behavior**
The search results page should load, at the very least, and should return results if there are any.

**Screenshots**
<img width="766" alt="Screen Shot 2020-03-13 at 17 31 49" src="https://user-images.githubusercontent.com/6436551/76645347-bc599d00-6550-11ea-9694-e46b48c8e6c8.png">

**Additional context**
An unnecessary `decodeURIComponent` is being performed on the query, as it has already been decoded by that point, so when it finds a standalone `%` it gets confused.

**Comment by chel-mhra** [comment]
Can you get this one over to Andy N to help QA please?

**Comment by chel-mhra** [comment]
@TimboTambo @ainemckay Can you get this one over to Andy N to help QA please?

**Comment by TimboTambo** [comment]
@chel-mhra sure! This wasn't included in the CR for this week so it'll only go out next week. It'll first be QA'd by someone in our team and then we'll identify with Andy N who would be best placed to test it from the business prior to next week's CAB.

**Comment by craiga** [comment]
✅ Passed QA
