### ISSUE TITLE
Searching for a PL number only returns SPC files

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#512]
**Describe the bug**
Searching for a PL number (e.g. "PL 30464/0140") only returns SPC files and not PIL's of that PL number.

**To Reproduce**
1) Search for `PL 30464/0140`
2) Observe only the single SPC file being returned
3) Search for `AMLODIPINE 10 MG TABLET`
4) Observe the top 3 results as the SPC that was returned in step 2, followed by 2 PIL files with the same PL number that should have been returned in step 2

**Expected behavior**
PIL files should also be returned when searching by PL number.

**Screenshots**
N/A

**Additional context**
I think this was introduced when the site was switched from `searchMode=any` to `searchMode=all`.

A. PL search first has the PL part copied out, normalized and added to the end of the search, e.g. a search for `PL 30464/0140` will be turned first into `PL 30464 0140` by having the `/` character removed and then turned into `PL 30464 0140 PL30464 0140` by having the full PL number added to the end. The search is then broken down into a fuzzy search when made to Azure search service, i.e.: `PL~1 PL^4 30464~1 30464^4 0140~1 0140^4 PL304640140~1 PL304640140^4`.

The search service is trying to match all the terms (`PL` and `30464` and `0140` and `PL304640140`). Both files have the PL number attached as metadata in `PL304640140` form so will associate strongly with the last selector. Neither file has `PL` `30464` or `0140` separately as metadata, so these terms weaken the search score. Only the SPC file has `PL 30464/0140` inside as content, so will associate slightly more than the PIL file with these terms, and just about get returned, whilst the PIL will not.

Updating the search logic so that the only thing that is searched for is the `PL304640140` part will ensure both SPC and PIL files get returned.

**Comment by majikandy** [comment]
Observed missing behavior in prod -  https://products.mhra.gov.uk

PIL entries for 
`AMLODIPINE 10 MG TABLET`  are not returned for the search terms `PL 30464/0140` and `AMLODIPINE 10 MG TABLET`

Observed fix in staging https://mhraproductsstaging.z33.web.core.windows.net/search/?query=pl%2043707%2F0005&page=1 - where the 2 PIL entries under the SIC file are returned correctly for both search terms.
