### ISSUE TITLE
 Observability | Azure monitor dashboard

### ISSUE THREAD

**Issue by pataruco** [MHRA/products#525]
## User want

As a technical user 
I want to visualize doc index updater using Azure monitor
So I can monitor and alert

## Technical acceptance criteria

Azure Monitor should have the tooling to visualise the [golden signals](https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/#xref_monitoring_golden-signals):

- [x] Latency
- [x] Traffic
- [x] Errors
- [x] Saturation

## Golden signals
> Taken from [Site Reliability Engineering book](https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/)

The four golden signals of monitoring are latency, traffic, errors, and saturation. If you can only measure four metrics of your user-facing system, focus on these four.

### Latency

Latency corresponds to the time it takes to serve a request.

We should separate success(200~300) and error latencies(400~500).

#### Way to measure it:

Store latency metrics as histogram time-series. We put our metrics into buckets that our exporters collect every minute. This way we can calculate the n-quantiles for our services’ latencies.

For `0 < n < 1` and a histogram with q values, the n-quantile of that histogram is the value that ranks `n*q` amongst the q values. This means the 0.5-quantile (aka. the median) for a histogram with x entries is the value for which half of the x values are smaller or equal.

Now, because we are using Prometheus, we must be very careful with the bucket sizes we pick. Prometheus allows for both linear and exponential bucket sizes. It doesn’t really matter which of the two options you choose. As long as you factor [estimation errors](https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation) in your choice, you’re good to go.

Prometheus doesn’t give the exact value for a quantile. It actually detects which of the buckets that quantile is in. Once it has done that, it uses linear interpolation to give an estimated value.

### Traffic

Count how many requests it receives every second. Now, because we only get new metrics every minute, we can’t get an exact value for a given second. We can use [Prometheus’ rate and irate](https://www.robustperception.io/irate-graphs-are-better-graphs) functions to work with averaged numbers of queries per second instead.

### Errors

The explicit error rate is pretty easy to compute, as we only need to divide HTTP **500**s served by the total number of requests served. Like for traffic, we use an averaged value.

### Saturation

To watch a service’s saturation, we need to determine its constraining parameters. We can measuring both CPU and Memory usage Kubernetes internals and [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics) allow us to get such metrics for containers.

> Snipets taken from [Distributed Monitoring 101: the “Four Golden Signals”](https://medium.com/forepaas/distributed-monitoring-101-the-four-golden-signals-305bbbc33d35)

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by sgrowe** [comment]
There are two PRs for this, one in the products repo and one in deployments:
- https://github.com/MHRA/products/pull/630
- https://github.com/MHRA/deployments/pull/12

**Comment by craiga** [comment]
As far as I can tell, there's nothing describing how to access this information.

There should be:
* something linking to the dashboard on Azure which shows these golden signals; and
* some description of how to see this information in [the logs documentation](https://github.com/MHRA/products/blob/master/infrastructure/docs/logs.md).
