### ISSUE TITLE
Job status not updated when message moved to dead letters

### ISSUE THREAD

**Issue by craiga** [MHRA/products#565]
**Describe the bug**

When a job fails after being retried a number of times, its status doesn't reflect this—it stays as "accepted".

**To Reproduce**

1. Configure the environment so that document creation will fail in some way. For example, change `STORAGE_ACCOUNT_NAME` to something that doesn't exist.
2. Submit a create document job.

**Actual Behaviour**

The job will be retried a number of times before being moved to dead letters.

The job status will not changed from "accepted".

**Expected Behaviour**

That the job failed is reflected somehow.

**Comment by rjkerrison** [comment]
We could easily fix this with a runner that checks the dead letters and updates state_manager for the ids it finds.

**Comment by craiga** [comment]
Documentation about dead letter queues: https://docs.microsoft.com/en-gb/azure/service-bus-messaging/service-bus-dead-letter-queues

It looks like we can use dead letter queues much like any other queue. I'm testing that out now.

### Option: treat dead letter queue as a queue of jobs to mark as failed

Once a job has been marked as failed, it's removed from the dead letter queue.

#### Questions

* Is it important that we keep the failed message around?
* Should we store the failed messages somewhere?

### Option: get a list of message IDs from the queue and marked each of those jobs as failed

#### Questions:

* Can we get a list of job IDs from the dead letter queues?
* Can we avoid getting the same job IDs more than once?
* Can this scale? What happens when we have 100,000 messages in the dead letter queue?

**Comment by rjkerrison** [comment]
Hi @craiga. I don't understand the second option, or at least how it would differ from the first option in practice.

The deadleterqueue is a queue, and you access it by appending `/$deadletterqueue` to the end of the regular queue name. I think it would be easy enough to have runners checking the deadletter queues and taking the IDs from the messages (which are identical to the messages from before they became dead letters) and doing the error update as you say.

The only question is how we handle persistence. We could do one of the following:

- leave them there, and just keep picking them up and pointlessly updating the Redis over and over
- put them on another queue to live forever
- log their details to _error_
- remove them and keep just the id as a record
- move them into Redis, where again they could live forever, or just for a few weeks by setting the time-to-live

I think moving them into Redis is the best option of the above, as its time-to-live feature lets us keep them there, inspectable, for a while after the failure in case we need to debug them, before cleaning them up itself..

**Comment by TimboTambo** [comment]
Yeah, while not so applicable for this first use case of using Sentinel (the timeout is going to be ~1 min before abandoning a job if it doesn't turn to "Done" or "Error"), it would be good to have the job status in Redis be eventually consistent with the actual job state, for any future consumers that have lower tolerances for quick feedback and as a quick way for ourselves to query particular jobs.

The actual logs would be a suitable place to store information about each job long-term, though.

According the documentation, it's possible we can access directly on the message from service bus the `BrokeredMessage.DeliveryCount` so the service bus client/message could have responsibility for updating the job state when the retry threshold has been reached?

**Comment by craiga** [comment]
To be clear, the first option would remove messages from the dead letter queue, the second option wouldn't.

**Comment by craiga** [comment]
> The actual logs would be a suitable place to store information about each job long-term, though.

Cool. This makes the first option the easiest IMO.

**Comment by craiga** [comment]
Regarding @TimboTambo's suggestion of having each worker be responsible for updating the job state, I did think about that but didn't put forward as an option as it's not how I'd expect a service bus client to work. I'd like to stick to [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by craiga** [comment]
Given that this isn't going to effect Sentinel, I'm wondering if this should be de-prioritised against the other, prioritised issues?

**Comment by majikandy** [comment]
Something retrying would make sense to have some indication this is happening and not just stuck on accepted ?  Even if we don't want to reveal that to the caller... perhaps Processing but a WARN in our logs for each retry until it finally puts and ERROR in our logs?

**Comment by craiga** [comment]
@majikandy Retries and expiry and handled by service bus. We can tell a message is being retried as they've got the same job/correlation ID. We could log the `BrokeredMessage.DeliveryCount` on each job, but I'm not sure that's important enough information.

**Comment by TimboTambo** [comment]
@craiga yeah I'm not clear where the responsibility most comfortably sits - it'd be easy to write but it doesn't feel clean for the consumer to deal with updating the job state based on number of retries (even if they already update job state to error based on other conditions). 

As you say, this is lower priority at the moment than other tasks on the backlog. It'd be great to come back and resolve later.

**Comment by craiga** [comment]
Moving to done as discussed in standup. This work should be picked up in #631.
