### ISSUE TITLE
"query" parameter should be for user search only

### ISSUE THREAD

**Issue by sandracoen1405** [MHRA/products#581]
### User want
As a user of Google Analytic
I want to distinguish user-created queries in the site search functionality
So that I can analyse user input

As a user of the site,
I want URL parameters to be semantic
So that I (and tools like Google's indexers) can understand the data structure more easily 

At the moment search queries, substance names, product names and  index letters are all captured in the "query" parameter for different pages. Only the search query is a true user-input query.

### Acceptance Criteria

- [x] _search_ used for freeform search terms on the search page
- [x] _letter_ used for the index page letter
- [x] _substance_ used for the substance page
- [x] _product_ used for the product page
- [x] only _search_ from the search terms page appears in Google Analytics site search
- [x] sitemap generator is updated

**Size**
M
**Value**
L
**Effort**
M

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
@sandracoen1405  Does the dataLayer variable `searchTerm` not provide this information already?

**Comment by sandracoen1405** [comment]
@rjkerrison tracking with data layer will only show keywords search, if an event has been recorded after the search

**Comment by m-doughty** [comment]
Picking this up now -- appears to be less of a bug and more of a feature.

**Comment by m-doughty** [comment]
This isn't strictly blocked, but we will need Kyle to grant access to Analytics panel so that this can be tested.

**Comment by TimboTambo** [comment]
@m-doughty just a reminder to update these parameters in the sitemap generator code too as that's easy to miss!

**Comment by m-doughty** [comment]
Have added that to the ACs, thanks @TimboTambo.

This task is a bit more effort than we thought because at some point, all of the searches were unified to a single Interface and I'm now having to un-unify them. Should be dev done today assuming no distractions.

**Comment by rjkerrison** [comment]
Checked all Acceptance Criteria and they're met, including the Google Analytics only seeing _search_ as a site search term.
