### ISSUE TITLE
Delete service treats every error like a job error

### ISSUE THREAD

**Issue by rjkerrison** [MHRA/products#601]
**Describe the bug**

The doc-index-updater create service, sensibly, retries when it encounters unknown errors.

Delete throws a hissy fit, and cancels the job forever.

**To Reproduce**

Set any key or name used by the Delete service to an incorrect value, or go offline for a minute or two. 

**Expected behavior**
Delete jobs are retried until the dead letter count is hit.

**Actual behaviour**
Watch as every delete job immediately becomes an error.

**Screenshots**

**Additional context**

# QA information
unit tests : make test

**For doc not found in index** 

1. scripts/delete.sh 123123123123
2. (assumes that id doesn't exist)
3. wait for the lease lock to expire
4. see that it is not retried

**For other errors**

1. find a way to create another error - maybe wrong search index api key?
2. scripts/delete.sh REAL_ID_HERE
3. wait for the lease lock to expire
4. see that it is retried

**Comment by majikandy** [comment]
@rjkerrison Do you have an example of something you think should retry? because something like 404 shouldn't retry, right ?

**Comment by majikandy** [comment]
**Things that should be retried**
404 - Since we get this currently from permissions error
401 - Fix api keys in env and this message is recoverable
503 - service unavailable, can recover when it comes back

**Things that should not be retried**
Document not found in index - should this even be an error scenario?

**Comment by craiga** [comment]
I can't think of anything else which shouldn't be retried, but can think of these error conditions:

* Blob described in search index not in storage (this might be 404?)
* We don't have permission to delete a blob (this might be 401?)

FYI, there's also https://github.com/MHRA/products/issues/561 which is tangentially related. It might be worth taking a look at that while you're looking at this?

**Comment by sgrowe** [comment]
Whilst trying to QA this I hit upon a bug where if I make an API request to delete a document and it fails to add the message to the service bus queue it still returns a 200 success response code.

Example curl request:
```
curl -vvv -X DELETE --user username:password http://localhost:8000/documents/CON1581657002878
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
* Server auth using Basic with user 'username'
> DELETE /documents/CON1581657002878 HTTP/1.1
> Host: localhost:8000
> Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 116
< date: Thu, 09 Apr 2020 13:14:35 GMT
< 
* Connection #0 to host localhost left intact
{"id":"3dcb5e82-a695-42db-b6f8-641da8540bbd","status":{"Error":{"message":"Failed to dispatch to queue","code":""}}}* Closing connection 0
```

Corresponding logs:

```
2020-04-09T13:14:35.817118+00:00  DEBUG document_manager{correlation_id="3dcb5e82-a695-42db-b6f8-641da8540bbd"}: doc_index_updater::state_manager::redis: Accepted
2020-04-09T13:14:35.819406+00:00  ERROR delete_document_handler::queue_job{correlation_id="3dcb5e82-a695-42db-b6f8-641da8540bbd"}: doc_index_updater::document_manager: Failed to dispatch to queue. Check environment variables align for queue names, policies and keys. Error: (HyperError(hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" }))))
2020-04-09T13:14:35.819870+00:00  DEBUG delete_document_handler::queue_job{correlation_id="3dcb5e82-a695-42db-b6f8-641da8540bbd"}: doc_index_updater::state_manager::redis: Error(: Failed to dispatch to queue)
2020-04-09T13:14:35.821991+00:00   INFO doc_index_updater: 127.0.0.1:52344 "DELETE /documents/CON1581657002878 HTTP/1.1" 200 "-" "curl/7.64.1" 413.532813ms
```

Would you prefer if I made this a separate issue though?

**Comment by majikandy** [comment]
@sgrowe yes feels unrelated to the logic in this card as this was about after gets to the being processed by the delete handler

**Comment by sgrowe** [comment]
Sure, created a new issue here: #647
