### ISSUE TITLE
Using 'back' in a browser from a results page

### ISSUE THREAD

**Issue by KyleCMHRA** [MHRA/products#64]
**Describe the bug**
If on a results page and then using 'back' on a browser (Chrome in this case), although the URL changes to remove the search element, the search results stay on screen

**To Reproduce**

1. Go to 'https://mhraproductsdev.z33.web.core.windows.net/.'
2. Perform any viable search
3. Scroll down to 'Click 'back' on your browser

**Expected behavior**
Clicking 'back' should take you back to the actual homepage, without a list of results displaying

**Screenshots**

**Additional context**

**Comment by rjkerrison** [comment]
Appears to have been fixed. Checked in both Chrome and Firefox.

**Comment by rjkerrison** [comment]
Fixed by #53
