### ISSUE TITLE
XML check-in requests with `&` in product name throws error

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#666]
**Describe the bug**
XML check-in requests with `&` in product name throws error throws 415 error (unsupported type). Likely because it isn't being decoded properly.

**To Reproduce**
Create check in request with following body:
```xml
<document>
<type>SPC</type>
<name>spc-doc_PL 18259-0009.pdf</name>
<author>sysadmin</author>
<pl_number>PL 18259/0009</pl_number>
<active_substances>
<active_substance>NAPHAZOLINE HYDROCHLORIDE</active_substance>
</active_substances>
<products>
<product>
MURINE RED & SORE EYES 0.12MG/ML EYE DROPS  SOLUTION
</product>
<product>
CLEAREYES 0.12MG/ML EYE DROPS  SOLUTION
</product>
</products>
</document>
```

**Expected behavior**
The request should be accepted and processed properly.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TimboTambo** [comment]
Any request with an ampersand in is actually an invalid request, so consumers of the API wishing to use XML must escape special characters properly, as outlined [here](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_xml_escape.html)

**Comment by craiga** [comment]
My initial thought is that this is invalid XML. Ampersands either need to be encoded as `&amp;` or inside a CDATA section (i.e. `<![CDATA[This & that]]>`.

**Comment by TimboTambo** [comment]
@craiga snap!
