### ISSUE TITLE
API is publicly accessible  

### ISSUE THREAD

**Issue by craiga** [MHRA/products#701]
## User want

As a 3rd party user I would like to able to access substance information through an API, so that I don't have to scrape the website and have easy access to the information.

### Customer and Technical acceptance criteria

- [ ] Self-documenting API is linked to from GitHub so it can be discovered by a third-party developer.
- Website makes use of GraphQL API

## Data - Potential impact

**Size**

S

**Value**

M

**Effort**

S

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
Related to the API which will be a result of #401, #403, #620, and #621.

**Comment by TimboTambo** [comment]
Tickets being tracked here: https://mhra.sharepoint.com/:x:/r/teams/t1a/ts8/_layouts/15/Doc.aspx?sourcedoc=%7B6FD18F7C-BB00-4D4D-A73C-415B352F7400%7D&file=Open%20tickets.xlsx&action=default&mobileredirect=true
