### ISSUE TITLE
About Page - 404 Error when returning to About Page after using Links on the About Page

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#73]
When accessing all of the links on the About Page  you are unable to return back to the About Page - 404 Error displayed

**To Reproduce**
1. Go to 'About Page' via the footer link
2. Click on ' any of the given links eg EMA website'
3. Go to the appropriate linked Page 
4. Press browser back button to return back to the About Page
5. Error 404 displayed

**Expected behavior**
Return back to the About Page

**Comment by rjkerrison** [comment]
When we generate the static site, /about.html is created, but /about/index.html is not. If we generated this, the navigation with back would work. I'll look into this fix.

**Comment by rjkerrison** [comment]
// next.config.js
    module.exports = {
      exportTrailingSlash: true,
    }

The next.js docs say to use `exportTrailingSlash` in `next.config.js` to generation `about/index.html` paths.

**Comment by rjkerrison** [comment]
@SteveLindsay461 looks like this has been fixed by #98
