### ISSUE TITLE
Exclusion zone around MHRA regulator logo

### ISSUE THREAD

**Issue by KyleCMHRA** [MHRA/products#75]
**Describe the bug**
The exclusion zone around the MHRA regulator logo is incorrect

**To Reproduce**

1. Go to the site
2. View the logo
3. Compare the exclusion zone to that detailed in the corporate branding guidelines (Rafa has these)

**Expected behavior**
The exclusion zone should be line with the branding guidelines

**Screenshots**
![desktop](https://user-images.githubusercontent.com/58690220/70522530-32f19380-1b39-11ea-9a2c-2e318a067f84.png)

**Additional context**

**Comment by roughprada** [comment]
design guidance here: https://zpl.io/259vXJQ

**Comment by roughprada** [comment]
After a conversation with @rjkerrison we would like to have padding around the logo that is half of the height of it.

the size of the logo and the space between the logo and the title will change to match the designs:
- desktop: https://zpl.io/259vXJQ
- mobile: https://zpl.io/VkzAAKv
