### ISSUE TITLE
PARs - Authentication group permissions

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#777]
### User want
As the owner of group permissions I would like to create a group for PARs form authentication and be able to add and remove members, so that the permissions list is always up to date and secure.

### Acceptance Criteria

**Customer acceptance criteria** 
- [ ] An authentication group for non-prod exists
- [ ] An authentication group for production exists
- [ ] A user within the PARs authentication group can log in
- [ ] A new user can be added to the PARs authentication group
- [ ] A user can be deleted from the PARs authentication group
- [ ] A user who is not part of the PARs authentication group is blocked from logging in
- [ ] Initial group should contain the list of users provided.

**Technical acceptance criteria**

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by TimboTambo** [comment]
Raised a ticket to get groups added - blocked until these are put in place
