### ISSUE TITLE
A-Z index on non-prod not working for IE11

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#778]
## Describe the bug
The A-Z list on non-prod has stopped working for IE11. Highlighted by Andy Snow following UAT for API Pod CR.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to 'product.mhra.gov.uk' using IE11
2. Click on the A-Z index list

### Expected behaviour

Should be able to go through to the substance pages from the index list

## Additional context

This was noted by Andy Snow following a sanity check on non-prod, before the release of the API Pod tickets.

**Comment by TimboTambo** [comment]
Substance index, substance and product pages not currently working. Message displayed in console "Syntax error". 

Suspect that issue could be resolved by using a polyfill - suggest trial using [react-app-polyfill](https://www.npmjs.com/package/react-app-polyfill) to see if it fixes issues.

**Comment by TimboTambo** [comment]
<img width="1346" alt="Screenshot 2020-05-12 at 11 59 23" src="https://user-images.githubusercontent.com/6436551/81677013-746bcf00-9448-11ea-8c02-c721667f0885.png">

**Comment by TimboTambo** [comment]
Introduced in commit 08057f48 - adding structured metadata to site. 
I think the problem lies in the `react-schemaorg` node module. Needs further investigation.

**Comment by TimboTambo** [comment]
Upgrading `react-schemaorg` from v `1.0.0` to `1.0.2` fixes this issue.

**Comment by rjkerrison** [comment]
This is fine for the current behaviour, but setting the GraphQL feature on with `useGraphQl=true` gives me the error below.

![screenshot of IE11 failing to call graphQl](https://user-images.githubusercontent.com/7150842/82219926-e1cea280-9915-11ea-918d-885f20295a4a.png)
