### ISSUE TITLE
Mobile version margins

### ISSUE THREAD

**Issue by KyleCMHRA** [MHRA/products#78]
**Describe the bug**
The left-margin, when viewed on phone size, is not consistent

**To Reproduce**

1. Go to the site
2. Reduce the browser down to 'phone' size
3. Look at the margin on the left-hand side, comparing the text, logo and search box wording

**Expected behavior**
There should be consistent margin

**Screenshots**
![iPhone](https://user-images.githubusercontent.com/58690220/70523172-5d901c00-1b3a-11ea-9517-93e5b58ad15b.png)

**Additional context**

**Comment by DimplePatel** [comment]
Margin also doesn't line up on the footer (Using an iphone 7/chrome):
<img width="289" alt="Screenshot 2019-12-10 at 15 52 43" src="https://user-images.githubusercontent.com/6122821/70545236-27b45d00-1b65-11ea-9106-cb793d0bc960.png">
