### ISSUE TITLE
Restrict public access to Azure Redis cache

### ISSUE THREAD

**Issue by TimboTambo** [MHRA/products#800]
## User want

As a business
I want to ensure access to services is as restricted as practically possible
So that I can ensure access is to authorised personnel and processes only

## Acceptance Criteria

Azure Redis Cache accessible by Doc Index Updater in cluster but not accessible otherwise.

**Size**
S

**Value**
S

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [x] Quality Assurance 
- [ ] Release and Validate

**Comment by rjkerrison** [comment]
@TimboTambo I'm able to stunnel to the non-prod redis locally. I left a new key `tim` for you if you'd like to look it up. _(Spoiler: it says `"hello"`.)_

**Comment by rjkerrison** [comment]
Now that the terraform has been applied in non-prod, I get `Error: Connection reset by peer` whenever I try to connect to redis via stunnel. 👍
