### ISSUE TITLE
PARs - DNS setup

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#810]
### User want
As a Medical Writer I can access the PARs upload / amend form from a defined MHRA URL.

### Acceptance Criteria

**Customer acceptance criteria** 
- [ ] There is a URL Medical Writers can access to upload and amend a new PAR
- [ ] Only internal MHRA IP addresses can access this URL?
- [ ] There is a URL structure for each page in the user flow
- [ ] Analytics?
**Technical acceptance criteria**

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by TimboTambo** [comment]
Requires the CDN to be deployed in production before a ticket can be raised. This is blocked until the CDN is deployed as part of next week's CR.

**Comment by TimboTambo** [comment]
Tickets being tracked here: https://mhra.sharepoint.com/:x:/r/teams/t1a/ts8/_layouts/15/Doc.aspx?sourcedoc=%7B6FD18F7C-BB00-4D4D-A73C-415B352F7400%7D&file=Open%20tickets.xlsx&action=default&mobileredirect=true
