### ISSUE TITLE
Responsive Layout - Text Overspill @75% and below  in Chrome

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#82]
When viewing the main search page in Chrome at 75%  Text started to overspill.
![image](https://user-images.githubusercontent.com/58432596/70528654-9cc46a00-1b46-11ea-92c9-10ea6e2b5c98.png)

Reducing the size futher caused loss of search text.
![image](https://user-images.githubusercontent.com/58432596/70528738-ce3d3580-1b46-11ea-92e8-a63dbee93194.png)

**Comment by sandracoen1405** [comment]
tested on sizzy and looks good
![image](https://user-images.githubusercontent.com/58703117/70553967-1b83cc00-1b74-11ea-8d50-ab245996a01a.png)

**Comment by DimplePatel** [comment]
This bug only occurs on windows it seems because it resizes fine on my mac

**Comment by pataruco** [comment]
Solve on #113 with one column layout merge

**Comment by DimplePatel** [comment]
@SteveLindsay461  i tested this again with browserstack and seems fixed, but maybe worth you checking too? As i dont have a windows computer

**Comment by SteveLindsay461** [comment]
I was able to reduce the view down to 33% using the browser zoom before I saw any text overspill
