### ISSUE TITLE
PARs - Upload success & error messages

### ISSUE THREAD

**Issue by sgrowe** [MHRA/products#822]
Had a chat with @roughprada and it was decided:
- on successful form submission, there shoud be a success screen as per [the design](https://app.zeplin.io/project/5dd51ae21205c944f8c1d35b/screen/5ebbfcbb5f5cec74857f3c70)
- if the there's an error submitting the form, an [error summary component](https://design-system.service.gov.uk/components/error-summary/) should be shown above the page heading on the "Check your answers" page  (this matches the GOV.UK design system)
- no loading screen (for the time being at least), just submit the form when they click "Accept and send" on the "Check your answers" page and then either show them the success screen or add an error summary to the top of the page and scroll the user up to the top so they can see it.
- Update the HTML title in the browser tab when an error is thrown (as per GDS guidelines).

**Comment by ainemckay** [comment]
Working in non-production by using authentication

![Screenshot 2020-06-03 at 14 41 18](https://user-images.githubusercontent.com/50627292/83751770-4d777600-a65f-11ea-9c8d-0d11bb5b218a.png)
