### ISSUE TITLE
Alphabetised Search - No. Files not Corresponding to Search

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#83]
**Describe the bug**
From and Alphabetised drill down Selected a product that indicated 2 Files however the Search results showed 3 exact matches rather than 2

**To Reproduce**
Steps to reproduce the behaviour:
1. Selected E
2. Click on ECHINACEA PURPUREA QUANTIFIED DRY EXTRACT'(2 Files
3. Select VITABIOTICS ECHINACEA TABLETS (2 files)
4.  3 Files shown with Exact Match rather than the 2

**Screenshots**
![image](https://user-images.githubusercontent.com/58432596/70529451-83bcb880-1b48-11ea-8bd0-2d39a0c17dfa.png)

**Additional context**

**Comment by m-doughty** [comment]
This is because PAR metadata doesn't actually contain product names. My suggestion is we just stop showing how many matches there are, because I agree that it's confusing.

Thoughts @MHRA/products-dev?

**Comment by roughprada** [comment]
Yes please @m-doughty let's remove the number of files right after that.

**Comment by DimplePatel** [comment]
In user testing we just had, the user found the number of files to be a useful feature. Maybe this ticket can be closed in favour of a fix for this: https://github.com/MHRA/products/issues/84 @ainemckay ?
