### ISSUE TITLE
Format product name in ALL CAPS

### ISSUE THREAD

**Issue by sgrowe** [MHRA/products#859]
Format should be: BRAND STRENGTH FORM-PL XXXXX/XXXX

See https://github.com/MHRA/products/issues/845

**Comment by ainemckay** [comment]
Hey 

Noticed the CAPS only appear in the title but CAPS do not appear in field when processed. 
![Screenshot 2020-06-03 at 09 07 34](https://user-images.githubusercontent.com/50627292/83613030-1fb90100-a57b-11ea-945f-7bc56d1639ee.png)
