### ISSUE TITLE
Do not allow duplicate license numbers

### ISSUE THREAD

**Issue by sgrowe** [MHRA/products#861]
The form (and ideally the backend too) should validate that you haven't entered the same license number twice

See point 3 in https://github.com/MHRA/products/issues/845

**Comment by KaylieGreen1607** [comment]
![Screen Shot 2020-06-02 at 10 54 10](https://user-images.githubusercontent.com/58774888/83506780-87117b00-a4bf-11ea-981e-a6e10400dc54.png)
Have tested on the upload a new form - Pass.
Now need to test on existing PAR form
