### ISSUE TITLE
New Homepage: Loses Yellow Card Information/Link when reduced

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#87]
When the new Homepage Layout is narrowed the Yellow Card Information and Link are lost from the Page completely

Yelow card information and Links should appear in the resized view

![image](https://user-images.githubusercontent.com/58432596/70536160-216ab480-1b56-11ea-9a47-e630f1c660df.png)
![image](https://user-images.githubusercontent.com/58432596/70536263-4c550880-1b56-11ea-9d2a-9249555235cb.png)

![image](https://user-images.githubusercontent.com/58432596/70536324-6262c900-1b56-11ea-99a4-9d4f7d089e6e.png)

**Comment by rjkerrison** [comment]
Looks like this was mistakenly removed. I'll put it back.
