### ISSUE TITLE
New Home Page:  Links on Page not working - 404 Errors

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#91]
**Describe the bug**
Neither the highlighted links are not working. Both  return a 404 error

![image](https://user-images.githubusercontent.com/58432596/70540471-40207980-1b5d-11ea-95e2-877df823ad66.png)

**Comment by DimplePatel** [comment]
"Further information about SPC-PILs and PARs" now works so it's just " Safety Public Assessment Reports" that leads to a 404 error

**Comment by DimplePatel** [comment]
tested on master - link now directs to the correct page
