### ISSUE TITLE
PARS release activities 

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#936]
## User want
As a developer, I want to make PARs accessible to Licensing users so they can upload PARs documents.

## Acceptance Criteria
- [ ] PARs site accessible to Licensing Team at pars.mhra.gov.uk
- [ ] Users can log in and submit PARs
- [ ] Updated PARs show up on site

### Technical acceptance criteria

- [ ] Custom domain added to CDN endpoint for pars.mhra.gov.uk
- [ ] SSL cert created and installed
- [ ] Site points to doc index updater in cluster in new subscription (already deployed)
- [ ] doc index updater in old subscription is updated to use Azure search service and storage containers in new subscription
- [ ] products website updated to point to Azure search service in new subscription

## Data - Potential impact

**Size**

**Value**

**Effort**

**Comment by TimboTambo** [comment]
Steps required for release:
- Add custom domain to PARs CDN in production for pars.mhra.gov.uk
- Enable SSL management by the CDN to create and provision an SSL certificate for the PARs domain
- Update configuration in doc-index-updater in old subscription to point to Azure search service and storage containers in new production subscription
- Update and release products.mhra.gov.uk website to point to Azure search service in new subscription
